# Generated by Django 2.1 on 2018-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_auto_20180822_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
