# Generated by Django 2.1 on 2018-09-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='api_key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
